# Секреты специально вынесены в отдельный файл, чтобы показать,
# что их создаёт другой человек. Сам разработчик правя 
# YAML-конфигурацию развёртывания Kubernetes не видит значения 
# секретов в этом файле.
apiVersion: v1
kind: Secret
metadata:
  name: postgresql-secret
type: Opaque
data:
  # Пары ключ-значение.
  # Значения в BASE64!!!
  POSTGRES_USER: bXl0ZW1wdXNlcg==
  POSTGRES_PASSWORD: bXl0ZW1wcGFzc3dvcmQ=
  POSTGRES_DB: bXl0ZW1wZGI=