services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=mydatabase'
      - 'POSTGRES_PASSWORD_FILE=/run/secrets/postgres-password
    ports:
      - '5432:5432'
    volumes:
      - ./init-postgres-schema.sql:/docker-entrypoint-initdb.d/init-postgres-schema.sql
    secrets:
      - postgres-password
  zipkin:
    image: 'openzipkin/zipkin:latest'
    ports:
      - '9411:9411'
  prometheus:
    image: 'prom/prometheus:latest'
    ports:
      - '9090:9090'
    volumes:
      - './prometheus.yml:/etc/prometheus/prometheus.yml'
secrets:
  postgres-password:
    file:./postgres-password.txt