services:
  frontend:
    image: nginx:1.29.4-alpine3.23
    # Список доступных сервису сетей.
    networks:
      - my-net
    ports:
      # Проброс порта 80 из контейнера Nginx
      # на порт 8085 хоста.
      - "8085:80"

# Сети
networks:
  # Одна сеть с именем my-net.
  # Все настройки сети по умолчанию.
  my-net: {}
    