# Базовый образ busybox версии 1.37.0.
FROM busybox:1.37.0
# Инструкция ENTRYPOINT в exec form.
# В данном примере просто выводит текст "Hello, world!"
# при запуске контейнера.с помощью команды echo.
ENTRYPOINT [ "echo", "Hello, world!" ]
