# Файл с описанием ресурсов Kubernetes.
apiVersion: v1
kind: Secret
metadata:
  name: lottery-check-pg-secret
type: Opaque
data:
  # lottery-check
  POSTGRES_USER: bG90dGVyeS1jaGVjaw==
  # password123
  POSTGRES_PASSWORD: cGFzc3dvcmQxMjM=