spring.application.name=spring-docker-compose
#logging.pattern.console=[%-5level] [%X{correlationId}][%X{traceId}-%X{spanId}] - %m%n
management.endpoints.web.exposure.include=health,prometheus
#management.tracing.baggage.correlation.fields=correlationId