FROM busybox:1.37.0
LABEL version=0.1
LABEL description="A simple Docker image with a single command"
LABEL maintainer="fedor@urvanov.ru"
LABEL ru.urvanov.my-super-label=This\ is\ a\ test\ label 
ENTRYPOINT [ "echo", "Hello, world!" ]
