# Версия API.
apiVersion: apps/v1
# Тип ресурса Deployment. В этом YAML-файле
# Описывается именно Deployment.
kind: Deployment
metadata:
  # Наименование Deployment
  name: pow-golang
spec:
  # Два одновременно работающих пода.
  replicas: 2
  # Поды для управления выбираются по стандартной 
  # стандартной метке наименования pow-golang.
  selector:
    matchLabels:
        app.kubernetes.io/name: pow-golang
  template:
    metadata:
      labels:
        # Каждому поду назначается метка с наименованием,
        # для того чтобы в последующем ReplicaSet мог
        # найти поды, которыми он управляет.
        app.kubernetes.io/name: pow-golang
    spec:
      containers:
      # Под содержит один контейнер
      # с наименованием pow-golang
      - name: pow-golang
        # Наименование нашего образа.
        image: urvanov/pow-golang
        # Для самостоятельно собираемых образов
        # важно выставлять политику выкачивания из
        # реестра IfNotPresent или Never.
        imagePullPolicy: IfNotPresent
