apiVersion: apps/v1
kind: Deployment
metadata:
  # Unique key of the Deployment instance
  name: pow-golang
spec:
  # 3 Pods should exist at all times.
  replicas: 3
  selector:
    matchLabels:
        app: pow-golang
  template:
    metadata:
      labels:
        # Apply this label to pods and default
        # the Deployment label selector to this value
        app: pow-golang
    spec:
      containers:
      - name: pow-golang
        # Run this image
        image: urvanov/pow-golang
        imagePullPolicy: IfNotPresent