apiVersion: apps/v1
# Тип ресурса.
kind: Deployment
metadata:
  # Наименование Deployment
  name: welcome-to-docker
spec:
  # Должно существовать три пода.
  replicas: 3
  # Селектор описывает, какими подами будет управлять создаваемый
  # ReplicaSet.
  selector:
    matchLabels:
        app: welcome-to-docker
        app.kubernetes.io/name: welcome-to-docker 
  template:
    metadata:
      labels:
        # Метки для созданных подов.
        # По этим меткам можно будет обращаться к
        # подам.
        app: welcome-to-docker
        app.kubernetes.io/name: welcome-to-docker 
    spec:
      # Контейнеры для пода
      containers:
      # В нашем поде только один контейнер welcome-to-docker.
      - name: welcome-to-docker
        # Образ для создания контейнеров.
        image: docker/welcome-to-docker
---
apiVersion: v1
# Тип ресурса.
# Сервис необходим для обращения к развёрнутым
# в подах контейнерам с балансировкой нагрузки.
kind: Service
metadata:
  # Наименование сервиса
  name: welcome-to-docker-service
spec:
  type: NodePort
  selector:
    # Сервис создаётся для подос со следующими
    # метками.
    app: welcome-to-docker
    app.kubernetes.io/name: welcome-to-docker 
  ports:
    - protocol: TCP
      # Сервис подключается к порту 80 подов.
      port: 80
