# Версия API.
# Обратите внимание, что apiVersion отличается от того,
# который использовался при описании Deployment.
apiVersion: batch/v1
# Тип ресурса Deployment. В этом YAML-файле
# Описывается именно Deployment.
kind: Job
metadata:
  # Наименование Deployment
  name: printenv
spec:
  template:
    spec:
      # Это обязательное поле. Без него объект
      # Job НЕ будет создан. 
      # возможные значения: Never, OnFailure.
      restartPolicy: Never
      containers:
      # Под содержит один контейнер
      # с наименованием printenv.
      - name: printenv
        # Наименование нашего образа.
        image: busybox:1.37.0
        # Для самостоятельно собираемых образов
        # важно выставлять политику выкачивания из
        # реестра IfNotPresent или Never.
        imagePullPolicy: IfNotPresent
        # Job printenv занимается тем, что просто выводит
        # содержимое всех переменных окружения
        # с помощью команды printenv. После чего Job
        # завершает своюработу.
        command: ["printenv"]

