services:
  frontend:
    build:
      context: ./frontend
      dockerfile: ../frontend.Dockerfile
    ports:
     - 8081:80
    develop:
      watch:
        - action: sync
          path: frontend/dist
          target: /usr/share/nginx/html
        - action: rebuild
          path: frontend/src
        - action: sync+exec
          path: nginx.conf
          target: /etc/nginx/nginx.conf
          exec:
            command: nginx -s reload
        - action: sync+exec
          path: default.conf
          target: /etc/nginx/conf.d/default.conf
          exec:
            command: nginx -s reload
  backend:
    build:
      context: ./backend
      dockerfile: ../backend.Dockerfile
    ports:
     - 8080:8080
    depends_on:
      - db
    develop:
      watch:
        - action: rebuild
          path: backend
  db:
    image: postgres:18.1-alpine3.23
    ports:
      - "5433:5432"
    volumes:
      - ./backend/docker//init.sql:/docker-entrypoint-initdb.d/init.sql
      - postgres_data:/var/lib/postgresql
    environment:
      POSTGRES_PASSWORD_FILE : /run/secrets/db_password 
      POSTGRES_USER : postgres
    secrets:
      - db_password

volumes:
  postgres_data:

secrets:
  db_password:
    file: db_password.txt
